### ISSUE TITLE
walk user through repo checklist items

### ISSUE THREAD

**Issue by thephilgray** [thephilgray/ginit-cli-tut#2]
Test for or scaffold the following files on the user's behalf before pushing:

- [ ] LICENSE
- [ ] README.md 
- [ ] .github/CONTRIBUTING.md
- [ ] .github/PULL_REQUEST_TEMPLATE.md
- [ ] .github/ISSUE_TEMPLATE.md

Walk user through creating each or selecting from template options.

**Comment by thephilgray** [comment]
templates/inspiration: 

**LICENSE**
https://choosealicense.com/
https://github.com/nishanths/license
https://github.com/tcnksm/license

**README**
https://github.com/dbader/readme-template

**CONTRIBUTING**
https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md
https://github.com/google/new-project

**PULL_REQUEST_TEMPLATE and ISSUE_TEMPLATE**
https://github.com/TalAter/open-source-templates
https://embeddedartistry.com/blog/2017/8/4/a-github-pull-request-template-for-your-projects
